spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
websiteURl: "https://api-starter.com"

server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /api/v1

logging:
  level:
    root: INFO
    org.springframework: INFO
    com.storefront: DEBUG
