spring:
  application:
    name: store-front

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  logging:
    level:
      org.hibernate.SQL: DEBUG
      org.hibernate.orm.jdbc.bind: TRACE
      org.hibernate.type.descriptor.sql: TRACE
      org.hibernate.orm.jdbc.extract: TRACE

  flyway:
    enabled: true
    locations: classpath:db/migration
