spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
websiteURl: "https://store-front.app"
server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /api/v1
logging:
  level:
    root: INFO
    org.springframework: INFO
    com.storefront: DEBUG
