alter table users
    change date_created created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL;

alter table users
    change date_updated updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL;;

ALTER TABLE addresses
    ADD COLUMN created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ADD COLUMN updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL;

ALTER TABLE categories
    ADD COLUMN created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ADD COLUMN updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL;

ALTER TABLE products
    ADD COLUMN created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ADD COLUMN updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL;

ALTER TABLE profiles
    ADD COLUMN created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ADD COLUMN updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL;

ALTER TABLE wishlist
    ADD COLUMN created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ADD COLUMN updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL;
